# Generated by Django 4.2.2 on 2023-06-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='some text', help_text='Enter field documentation', max_length=20, unique=True)),
                ('number', models.PositiveSmallIntegerField(default=0)),
                ('x', models.TextField()),
            ],
        ),
    ]
